name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate Light Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics-light.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: salihoglueyup
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Istanbul
          config_theme: light
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_lines: yes

      - name: Generate Dark Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics-dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: salihoglueyup
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Istanbul
          config_theme: dark
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_lines: yes
